apiVersion: v1
kind: ReplicationController
metadata:
  name: my-server-replicacontroller
spec:
  replicas: 2
  selector:
    app: my-server-controller
  template:
    metadata:
      labels:
        app: my-server-controller
    spec:
      containers:
      - name: my-server-controller
        image: nginx:1.15.4-alpine
        ports:
        -  containerPort: 80
