apiVersion: v1
kind: Pod
metadata:
  name: staticweb
  labels:
    app: staticweb
spec:
  containers:
    - name: staticweb
      image: abdelhalim/static_web
      args:
        - "-http=0.0.0.0:80"
      ports:
        - name: http
          containerPort: 80
      resources:
        limits:
          cpu: 0.2
          memory: "10Mi"
